[package]
name = "voxelize-protocol"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = {version = "1.0.183", features = ["derive"]}
serde_json = "1.0.105"
prost = "0.11.9"
prost-wkt = "0.4.2"
prost-wkt-types = "0.4.2"


[build-dependencies]
prost-build = "0.11.9"
prost-wkt-build = "0.4.2"